language: cpp

sudo: required

services:
  - docker

before_install:
  - docker build -t fortress .

jobs:
  include:
    - stage: build and test
      script: docker run --rm fortress /bin/sh -c 'make && make test'
