language: cpp
before_install:
    - sudo apt-get install libglfw3-dev 
    - sudo apt-get install libsoil-dev
    - sudo apt-get install libgoogle-glog-dev
    - sudo apt-get install libyaml-cpp-dev
    - sudo apt-get install liblua5.3
    - sudo apt-get install cppcheck
jobs:
    include:
        - stage: build
          script: make build
        - stage: test
          script: make test
        - stage: analysis
          script: make lint
