# Site settings
title: Fortress - A Roguelike
email: pkuehne@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
    Fortress is an ASCII roguelike written in C++ using OpenGL and GLUT
baseurl: "/fortress" # the subpath of your site, e.g. /blog/
url: "http://pkuehne.github.com" # the base hostname & protocol for your site
twitter_username:
github_username:  pkuehne

# Build settings
markdown: kramdown
